name: Wicked Waifus Automation

on:
  schedule:
    - cron: 30 * * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-fetching:
    runs-on: ubuntu-latest
    steps:
      - name: Save Current Date To GitHub Environment
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: ${{ 'https://prod-alicdn-' }}${{ 'gamestarter.' }}${{ 'ku' }}${{ 'ro' }}${{ 'ga' }}${{ 'me' }}${{ '.com/launcher/game/G153/50004_obOHXFrFanqsaIEOmuKroCcbZkQRBC7c/index.json' }}
          save-location: "fetch/wuwa/latest/"
          save-name: result-latest
      - name: Code File Prettier
        run: |
          npx prettier --write fetch/wuwa/**/*.json
      - name: Compare with last file
        id: compare
        run: |
          LAST_FILE=$(find fetch/wuwa -maxdepth 1 -type f -name "*.json" -printf "%T@ %p\n" 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2-)
          TARGET_FILE="fetch/wuwa/latest/result-latest.json"

          if [ -n "$LAST_FILE" ] && [ -f "$TARGET_FILE" ]; then
            if diff -q "$LAST_FILE" "$TARGET_FILE" >/dev/null; then
              echo "same=true" >> "$GITHUB_ENV"
            else
              echo "same=false" >> "$GITHUB_ENV"
            fi
          else
            echo "same=false" >> "$GITHUB_ENV"
          fi
      - name: Move new file if different
        if: env.same == 'false'
        run: |
          mkdir -p fetch/wuwa
          cp fetch/wuwa/latest/result-latest.json fetch/wuwa/result-${{ env.CURRENT_DATE }}.json
      - name: Commit Changes
        if: env.same == 'false'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          arr[0]="Daily Fetch Commit Automation (Bot) 🏠"
          arr[1]="Daily Fetch Commit Automation (Bot) 🏘️"
          arr[2]="Daily Fetch Commit Automation (Bot) 🏡"
          arr[3]="Daily Fetch Commit Automation (Bot) 🏨"
          arr[4]="Daily Fetch Commit Automation (Bot) 🏪"
          arr[5]="Daily Fetch Commit Automation (Bot) 🏦"
          arr[6]="Daily Fetch Commit Automation (Bot) 🏢"
          arr[7]="Daily Fetch Commit Automation (Bot) 🏭"
          rand=$[$RANDOM % ${#arr[@]}]

          git add ./fetch/wuwa/
          git commit -m "${arr[$rand]}"
      - name: GitHub Push
        if: env.same == 'false'
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
